# Nikita Kouevda
# 2014/08/24

title: Nikita Kouevda
author: Nikita Kouevda
email: nkouevda@gmail.com
permalink: pretty
exclude: [README.md]
defaults:
  - scope:
      path: ''
      type: page
    values:
      layout: page
  - scope:
      path: ''
      type: post
    values:
      layout: post
