# Nikita Kouevda
# 2014/05/26

title: Nikita Kouevda
author: Nikita Kouevda
email: nkouevda@gmail.com
permalink: pretty
exclude: [README.md]
defaults:
  -
    scope:
      path: blog
    values:
      layout: post
