title: Nikita Kouevda
email: nkouevda@gmail.com
permalink: pretty
exclude: [README.md]
defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: page
  - scope:
      path: ''
      type: posts
    values:
      layout: post
